# build Go
FROM golang:1.20-alpine AS build

WORKDIR /app/backend
COPY go.mod go.sum main.go ./
RUN go mod download
COPY . .
RUN go build -o main

FROM scratch
COPY --from=build /app/backend/main /backend/
COPY .env /backend/
WORKDIR /backend/
EXPOSE 9000
ENTRYPOINT [ "./main" ]